[package]
name = "pigeonv"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = "0.16.1"
axum = { version = "0.8.9", features = ["query"] }
chrono = { version = "0.4.45", features = ["serde"] }
serde = { version = "1.0.229", features = ["serde_derive"] }
tokio = { version = "1.53.1", features = ["rt-multi-thread"] }
tower-http = { version = "0.7.1", features = ["fs"] }
